[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rlPx4Controller"
authors = [{name = "FP-Flight", email = "rlpx4controller@outlook.com"}]
dynamic = ["version", "description"]